In [6]:
A = [[1, 0], [0, 1]]
B = [[1, 1], [1, 1]]
A + B

[[1, 0], [0, 1], [1, 1], [1, 1]]

In [7]:
# list 와 numpy의 차이
import numpy as np
A = np.array([[1, 0], [0, 1]])
B = np.array([[1, 1], [1, 1]])
A + B

array([[2, 1],
       [1, 2]])

In [8]:
# numpy vector, 1행인 matrix가 아니다.
# shape, ndim 속성
import numpy as np

A = np.array([1, 2, 3])
B = np.array([4, 5, 6])
print("A ==", A, ", B ==", B)
print("vector A shape ==", A.shape, ", vector B shape ==", B.shape)
print("vector A dimension ==", A.ndim, ", vector B dimension ==", B.ndim)

A == [1 2 3] , B == [4 5 6]
vector A shape == (3,) , vector B shape == (3,)
vector A dimension == 1 , vector B dimension == 1


In [12]:
# numpy matrix
# shape은 행과 열을 표시해줌
import numpy as np

A = np.array([[1, 2, 3], [4, 5, 6]])
B = np.array([[-1, -2, -3], [-4, -5, -6]])
print("matrix A =", A)
print("matrix B =", B)
print("matrix A shape ==", A.shape, ", matrix B shape ==", B.shape)
print("matrix A dimension ==", A.ndim, ", matrix B dimension ==", B.ndim)

matrix A = [[1 2 3]
 [4 5 6]]
matrix B = [[-1 -2 -3]
 [-4 -5 -6]]
matrix A shape == (2, 3) , matrix B shape == (2, 3)
matrix A dimension == 2 , matrix B dimension == 2


In [13]:
# numpy는 편리한 산술연산을 제공
# 각 원소에 대응되는 원소끼리 연산을 수행
import numpy as np

A = np.array([1, 2, 3])
B = np.array([4, 5, 6])

print("A ==", A, ", B ==", B)
print("A + B ==", A + B)
print("A - B ==", A - B)
print("A * B ==", A * B)
print("A / B ==", A / B)

A == [1 2 3] , B == [4 5 6]
A + B == [5 7 9]
A - B == [-3 -3 -3]
A * B == [ 4 10 18]
A / B == [0.25 0.4  0.5 ]


In [15]:
# reshape()은 shape을 변경해줌
import numpy as np

C = np.array([1, 2, 3])
print("C.shape ==", C.shape)
C = C.reshape(1, 3)
print("C.shape ==", C.shape)

D = np.array([[1, 2, 3], [4, 5, 6]])
print("D.shape ==", D.shape)
D = D.reshape(3, 2)
print("D shape ==", D.shape)

C.shape == (3,)
C.shape == (1, 3)
D.shape == (2, 3)
D shape == (3, 2)


In [16]:
# matrix에서 reshape(-1, a)는 a열을 갖도록 행을 적절히 변환
import numpy as np

A = np.array([[1, 2, 3, 4],
             [10, 20, 30, 40],
             [100, 200, 300, 400]])
print(A.shape)

B = A.reshape(-1, 3)
print("B shape ==", B.shape)
print(B)

C = A.reshape(-1, 6)
print("C shape ==", C.shape)
print(C)

(3, 4)
B shape == (4, 3)
[[  1   2   3]
 [  4  10  20]
 [ 30  40 100]
 [200 300 400]]
C shape == (2, 6)
[[  1   2   3   4  10  20]
 [ 30  40 100 200 300 400]]


In [18]:
# Broadcast, matrix의 shape이 서로 다른 경우에도 사칙연산이 가능하도록 확장하는 기능
# 차원이 작은 쪽이 큰 쪽에 맞춰 행단위로, 반복적으로 크기가 확장
import numpy as np

A = np.array([[1, 2], [3, 4]])
B = 5
print(A + B)

C = np.array([[1, 2], [3, 4]])
D = np.array([4, 5])
print(C + D)

[[6 7]
 [8 9]]
[[5 7]
 [7 9]]


In [2]:
# Transpose 사용법
# .T 명심
import numpy as np

A = np.array([[1, 2], [3, 4], [5, 6]])
B = A.T

print("A.shape ==", A.shape)
print("B.shape ==", B.shape)
print(A)
print(B)

A.shape == (3, 2)
B.shape == (2, 3)
[[1 2]
 [3 4]
 [5 6]]
[[1 3 5]
 [2 4 6]]


In [5]:
# 왜 vector를 1 * n matrix로 생각하면 안되는지 보여주는 예제
import numpy as np

C = np.array([1, 2, 3, 4, 5])
D = C.T
print("C.shape ==", C.shape , ", D.shape ==", D.shape)

# reshpae을 통해 vector를 matrix로 변경
E = C.reshape(1, 5)
F = E.T
print("E.shape ==", E.shape, " , F.shape ==", F.shape)

C.shape == (5,) , D.shape == (5,)
E.shape == (1, 5)  , F.shape == (5, 1)


In [6]:
import numpy as np

A = np.array([[1, 2, 3], [4, 5, 6]])
B = np.array([[-1, -2], [-3, -4], [-5, -6]])
C = np.dot(A, B)

print("A shape ==", A.shape, ", B.shape ==", B.shape)
print("C.shape ==", C.shape)
print(C)

A shape == (2, 3) , B.shape == (3, 2)
C.shape == (2, 2)
[[-22 -28]
 [-49 -64]]
